In [1]:
import quandl
data = quandl.get('NSE/OIL',)

In [3]:
?quandl.get

In [4]:
data

,Open,High,Low,Last,Close,Total Trade Quantity,Turnover (Lacs)
Date,,,,,,,
2009-09-30,1096.00,1156.70,1090.00,1135.00,1141.20,19748012.0,223877.07
2009-10-01,1102.00,1173.70,1102.00,1167.00,1166.35,3074254.0,35463.78
2009-10-05,1152.00,1165.90,1136.60,1143.00,1140.55,919832.0,10581.13
2009-10-06,1149.80,1157.20,1132.10,1143.30,1144.90,627957.0,7185.90
2009-10-07,1153.80,1160.70,1140.00,1141.45,1141.60,698216.0,8032.98
2009-10-08,1145.00,1179.80,1142.00,1178.10,1170.20,788173.0,9138.99
2009-10-09,1176.00,1210.00,1165.00,1183.00,1195.65,1047417.0,12449.44
2009-10-12,1184.00,1210.00,1176.00,1193.00,1195.70,464697.0,5551.35
2009-10-14,1198.00,1227.75,1185.00,1192.50,1190.45,581221.0,7015.84
2009-10-15,1198.00,1204.90,1180.05,1184.90,1184.55,301790.0,3593.52
2009-10-16,1188.65,1203.00,1182.00,1191.10,1191.00,313011.0,3735.12
2009-10-17,1240.00,1240.00,1180.00,1189.10,1189.80,35143.0,418.95
2009-10-20,1196.00,1203.50,1172.00,1174.00,1177.85,156941.0,1861.75
2009-10-21,1184.00,1194.00,1157.00,1166.00,1166.10,309098.0,3657.14
2009-10-22,1165.00,1184.40,1158.00,1168.00,1164.95,338413.0,3973.97
2009-10-23,1174.90,1179.45,1161.20,1165.00,1164.70,216929.0,2538.68
2009-10-26,1151.30,1175.00,1145.00,1158.00,1156.40,209553.0,2423.58
2009-10-27,1150.05,1150.05,1114.20,1140.00,1140.35,407594.0,4635.23
2009-10-28,1141.00,1141.00,1111.00,1130.20,1130.20,243141.0,2745.53
2009-10-29,1125.25,1137.90,1115.10,1132.00,1132.25,65246.0,736.80
2009-10-30,1145.00,1145.00,1110.00,1111.90,1120.60,117100.0,1325.22
2009-11-03,1102.00,1127.50,1102.00,1120.95,1120.00,179969.0,2013.91
2009-11-04,1124.90,1159.00,1120.00,1150.50,1150.85,284546.0,3248.87
2009-11-05,1127.00,1154.00,1127.00,1153.00,1148.90,49813.0,568.75
2009-11-06,1155.00,1168.55,1146.25,1160.00,1156.50,295089.0,3421.96
2009-11-09,1150.05,1167.00,1150.05,1160.05,1165.05,93970.0,1090.62
2009-11-10,1157.00,1169.90,1142.00,1149.00,1147.75,286131.0,3301.75
2009-11-11,1147.00,1191.00,1145.40,1173.05,1181.35,325326.0,3788.43
2009-11-12,1190.00,1193.00,1170.00,1185.00,1182.60,143567.0,1698.72
2009-11-13,1175.00,1223.70,1168.00,1189.00,1194.45,440047.0,5277.68
...,...,...,...,...,...,...,...
2018-03-16,335.15,340.80,333.60,340.00,337.25,595571.0,2005.22
2018-03-19,337.40,345.10,335.30,339.00,337.00,892681.0,3037.49
2018-03-20,338.10,338.10,324.50,328.00,327.10,689486.0,2285.78
2018-03-21,330.00,334.75,330.00,332.75,332.25,377984.0,1256.34
2018-03-22,334.00,344.55,334.00,343.90,341.35,1513899.0,5139.83
2018-03-23,339.35,352.00,332.25,349.50,349.95,5043261.0,17318.61
2018-03-26,353.00,353.00,337.00,341.00,342.45,1812181.0,6252.15
2018-03-27,215.00,221.95,213.00,216.80,216.80,2742078.0,5949.49
2018-03-28,215.10,218.90,214.10,218.10,216.35,2219838.0,4797.22
2018-04-02,220.50,231.00,216.30,228.00,227.05,1524529.0,3418.23
2018-04-03,225.00,225.00,220.25,221.00,221.05,789750.0,1755.37
2018-04-04,223.90,223.90,215.10,215.80,215.80,1002537.0,2190.17
2018-04-05,216.50,218.50,216.10,217.40,217.50,983714.0,2137.66
2018-04-06,216.55,219.95,216.00,217.80,217.60,821043.0,1788.81
2018-04-09,218.00,218.00,213.50,216.05,216.15,802179.0,1728.05
2018-04-10,217.40,218.25,216.65,217.20,217.20,693885.0,1507.30
2018-04-11,219.05,227.00,218.90,219.95,220.00,3053178.0,6811.08
2018-04-12,221.65,222.90,215.60,217.60,217.85,819229.0,1786.97
2018-04-13,218.00,220.65,217.50,218.80,219.50,1771507.0,3880.91
2018-04-16,216.70,218.95,213.00,217.40,217.90,459260.0,1000.78
2018-04-17,217.40,218.80,216.15,217.95,217.95,415033.0,904.45
2018-04-18,218.70,219.00,216.85,217.85,218.10,391209.0,853.24
2018-04-19,219.80,226.25,219.80,226.00,225.15,2167454.0,4854.78
2018-04-20,225.95,231.45,224.90,229.30,230.45,1260962.0,2876.67
2018-04-23,230.25,233.45,227.25,231.45,231.60,897579.0,2078.82
2018-04-24,234.45,240.90,232.10,237.95,237.05,1824432.0,4314.79
2018-04-25,236.50,236.50,232.70,234.80,233.75,775443.0,1814.05
2018-04-26,236.25,238.40,232.50,234.10,235.15,1805405.0,4249.55
2018-04-27,236.50,236.50,226.45,231.15,231.30,783876.0,1807.17
2018-04-30,229.25,233.10,228.10,232.70,232.45,440462.0,1018.54